// 英语学习包(4 个词库包共 549 词:基础 320 + 主题场景 120 + 高频 85 + 易错 24)
// 由语言选择器动态加载;直接用 window 赋值,避免重复声明
// level 字段为欧洲语言共同参考框架等级:A1 / A2 / B1 / B2 / C1 / C2

window.LETTER_GROUPS = null; // 英语不提供字母发音卡片

// 词库包注册表(与俄语同构:4 个包独立学习、独立统计、独立复习)
window.VOCAB_PACKS = [
  { id: 'base', name: '基础词汇', data: 'VOCAB', desc: 'CEFR A1–C2 分级词汇' },
  { id: 'scenes', name: '主题场景', data: 'VOCAB_SCENES', desc: '30 个生活场景实用词' },
  { id: 'freq', name: '高频词汇', data: 'VOCAB_FREQ', desc: '按频率精选的高频词' },
  { id: 'mistakes', name: '易错口语', data: 'VOCAB_MISTAKES', desc: '易混词·搭配·重音·用法辨析' },
];

window.VOCAB = [
  // 问候
  { cat: '问候', ru: 'hello', zh: '你好', level: 'A1' },
  { cat: '问候', ru: 'hi', zh: '嗨', level: 'A1' },
  { cat: '问候', ru: 'goodbye', zh: '再见', level: 'A1' },
  { cat: '问候', ru: 'good morning', zh: '早上好', level: 'A1' },
  { cat: '问候', ru: 'good night', zh: '晚安', level: 'A1' },
  { cat: '问候', ru: 'thank you', zh: '谢谢', level: 'A1' },
  { cat: '问候', ru: 'please', zh: '请', level: 'A1' },
  { cat: '问候', ru: 'sorry', zh: '对不起', level: 'A1' },
  { cat: '问候', ru: 'yes', zh: '是', level: 'A1' },
  { cat: '问候', ru: 'no', zh: '不', level: 'A1' },
  { cat: '问候', ru: 'good evening', zh: '晚上好', level: 'A1' },
  { cat: '问候', ru: 'welcome', zh: '欢迎', level: 'A1' },
  { cat: '问候', ru: 'of course', zh: '当然', level: 'A1' },
  { cat: '问候', ru: 'excuse me', zh: '打扰一下', level: 'A1' },
  { cat: '问候', ru: 'see you', zh: '再见(非正式)', level: 'A1' },
  { cat: '问候', ru: 'congratulations', zh: '祝贺', level: 'A2' },
  // 代词
  { cat: '代词', ru: 'I', zh: '我', level: 'A1' },
  { cat: '代词', ru: 'you', zh: '你 / 你们', level: 'A1' },
  { cat: '代词', ru: 'he', zh: '他', level: 'A1' },
  { cat: '代词', ru: 'she', zh: '她', level: 'A1' },
  { cat: '代词', ru: 'we', zh: '我们', level: 'A1' },
  { cat: '代词', ru: 'they', zh: '他们', level: 'A1' },
  { cat: '代词', ru: 'what', zh: '什么', level: 'A1' },
  { cat: '代词', ru: 'who', zh: '谁', level: 'A1' },
  { cat: '代词', ru: 'this', zh: '这个', level: 'A1' },
  { cat: '代词', ru: 'that', zh: '那个', level: 'A1' },
  { cat: '代词', ru: 'these', zh: '这些', level: 'A1' },
  { cat: '代词', ru: 'those', zh: '那些', level: 'A1' },
  { cat: '代词', ru: 'everything', zh: '一切', level: 'A1' },
  { cat: '代词', ru: 'nothing', zh: '没什么', level: 'A1' },
  // 数字
  { cat: '数字', ru: 'one', zh: '一', level: 'A1' },
  { cat: '数字', ru: 'two', zh: '二', level: 'A1' },
  { cat: '数字', ru: 'three', zh: '三', level: 'A1' },
  { cat: '数字', ru: 'four', zh: '四', level: 'A1' },
  { cat: '数字', ru: 'five', zh: '五', level: 'A1' },
  { cat: '数字', ru: 'ten', zh: '十', level: 'A1' },
  { cat: '数字', ru: 'six', zh: '六', level: 'A1' },
  { cat: '数字', ru: 'seven', zh: '七', level: 'A1' },
  { cat: '数字', ru: 'eight', zh: '八', level: 'A1' },
  { cat: '数字', ru: 'nine', zh: '九', level: 'A1' },
  { cat: '数字', ru: 'eleven', zh: '十一', level: 'A1' },
  { cat: '数字', ru: 'twelve', zh: '十二', level: 'A1' },
  { cat: '数字', ru: 'twenty', zh: '二十', level: 'A1' },
  { cat: '数字', ru: 'hundred', zh: '百', level: 'A1' },
  { cat: '数字', ru: 'thousand', zh: '千', level: 'A1' },
  { cat: '数字', ru: 'first', zh: '第一', level: 'A1' },
  // 常用动词
  { cat: '常用动词', ru: 'be', zh: '是 / 在', level: 'A1' },
  { cat: '常用动词', ru: 'have', zh: '有', level: 'A1' },
  { cat: '常用动词', ru: 'do', zh: '做', level: 'A1' },
  { cat: '常用动词', ru: 'go', zh: '去', level: 'A1' },
  { cat: '常用动词', ru: 'come', zh: '来', level: 'A1' },
  { cat: '常用动词', ru: 'eat', zh: '吃', level: 'A1' },
  { cat: '常用动词', ru: 'like', zh: '喜欢', level: 'A1' },
  { cat: '常用动词', ru: 'want', zh: '想要', level: 'A1' },
  { cat: '常用动词', ru: 'speak', zh: '说', level: 'A1' },
  { cat: '常用动词', ru: 'study', zh: '学习', level: 'A2' },
  { cat: '常用动词', ru: 'drink', zh: '喝', level: 'A1' },
  { cat: '常用动词', ru: 'sleep', zh: '睡觉', level: 'A1' },
  { cat: '常用动词', ru: 'read', zh: '读', level: 'A1' },
  { cat: '常用动词', ru: 'write', zh: '写', level: 'A1' },
  { cat: '常用动词', ru: 'listen', zh: '听', level: 'A1' },
  { cat: '常用动词', ru: 'watch', zh: '看(电视/比赛)', level: 'A1' },
  { cat: '常用动词', ru: 'buy', zh: '买', level: 'A1' },
  { cat: '常用动词', ru: 'sell', zh: '卖', level: 'A2' },
  { cat: '常用动词', ru: 'open', zh: '打开', level: 'A1' },
  { cat: '常用动词', ru: 'close', zh: '关闭', level: 'A1' },
  { cat: '常用动词', ru: 'begin', zh: '开始', level: 'A1' },
  { cat: '常用动词', ru: 'finish', zh: '完成', level: 'A1' },
  { cat: '常用动词', ru: 'learn', zh: '学习', level: 'A1' },
  { cat: '常用动词', ru: 'teach', zh: '教', level: 'A1' },
  { cat: '常用动词', ru: 'help', zh: '帮助', level: 'A1' },
  { cat: '常用动词', ru: 'know', zh: '知道', level: 'A1' },
  { cat: '常用动词', ru: 'think', zh: '想 / 认为', level: 'A1' },
  { cat: '常用动词', ru: 'feel', zh: '感觉', level: 'A1' },
  { cat: '常用动词', ru: 'meet', zh: '遇见', level: 'A1' },
  { cat: '常用动词', ru: 'bring', zh: '带来', level: 'A1' },
  // 常用名词
  { cat: '常用名词', ru: 'water', zh: '水', level: 'A1' },
  { cat: '常用名词', ru: 'book', zh: '书', level: 'A1' },
  { cat: '常用名词', ru: 'house', zh: '房子', level: 'A1' },
  { cat: '常用名词', ru: 'friend', zh: '朋友', level: 'A1' },
  { cat: '常用名词', ru: 'time', zh: '时间', level: 'A1' },
  { cat: '常用名词', ru: 'day', zh: '天 / 白天', level: 'A1' },
  { cat: '常用名词', ru: 'work', zh: '工作', level: 'A2' },
  { cat: '常用名词', ru: 'bread', zh: '面包', level: 'A1' },
  { cat: '常用名词', ru: 'milk', zh: '牛奶', level: 'A1' },
  { cat: '常用名词', ru: 'tea', zh: '茶', level: 'A1' },
  { cat: '常用名词', ru: 'coffee', zh: '咖啡', level: 'A1' },
  { cat: '常用名词', ru: 'apple', zh: '苹果', level: 'A1' },
  { cat: '常用名词', ru: 'dog', zh: '狗', level: 'A1' },
  { cat: '常用名词', ru: 'cat', zh: '猫', level: 'A1' },
  { cat: '常用名词', ru: 'school', zh: '学校', level: 'A1' },
  { cat: '常用名词', ru: 'city', zh: '城市', level: 'A1' },
  { cat: '常用名词', ru: 'country', zh: '国家', level: 'A1' },
  { cat: '常用名词', ru: 'money', zh: '钱', level: 'A1' },
  { cat: '常用名词', ru: 'family', zh: '家庭', level: 'A1' },
  { cat: '常用名词', ru: 'mother', zh: '妈妈', level: 'A1' },
  { cat: '常用名词', ru: 'father', zh: '爸爸', level: 'A1' },
  { cat: '常用名词', ru: 'brother', zh: '兄弟', level: 'A1' },
  { cat: '常用名词', ru: 'sister', zh: '姐妹', level: 'A1' },
  { cat: '常用名词', ru: 'door', zh: '门', level: 'A1' },
  { cat: '常用名词', ru: 'window', zh: '窗户', level: 'A1' },
  { cat: '常用名词', ru: 'table', zh: '桌子', level: 'A1' },
  { cat: '常用名词', ru: 'chair', zh: '椅子', level: 'A1' },
  // 形容词
  { cat: '形容词', ru: 'good', zh: '好的', level: 'A1' },
  { cat: '形容词', ru: 'bad', zh: '坏的', level: 'A1' },
  { cat: '形容词', ru: 'big', zh: '大的', level: 'A1' },
  { cat: '形容词', ru: 'small', zh: '小的', level: 'A1' },
  { cat: '形容词', ru: 'new', zh: '新的', level: 'A1' },
  { cat: '形容词', ru: 'old', zh: '旧的 / 年老的', level: 'A1' },
  { cat: '形容词', ru: 'young', zh: '年轻的', level: 'A1' },
  { cat: '形容词', ru: 'happy', zh: '快乐的', level: 'A1' },
  { cat: '形容词', ru: 'sad', zh: '悲伤的', level: 'A1' },
  { cat: '形容词', ru: 'beautiful', zh: '美丽的', level: 'A1' },
  { cat: '形容词', ru: 'ugly', zh: '丑陋的', level: 'B1' },
  { cat: '形容词', ru: 'tall', zh: '高的', level: 'A1' },
  { cat: '形容词', ru: 'short', zh: '矮的 / 短的', level: 'A1' },
  { cat: '形容词', ru: 'long', zh: '长的', level: 'A1' },
  { cat: '形容词', ru: 'fast', zh: '快的', level: 'A1' },
  { cat: '形容词', ru: 'slow', zh: '慢的', level: 'A1' },
  { cat: '形容词', ru: 'hot', zh: '热的', level: 'A1' },
  { cat: '形容词', ru: 'cold', zh: '冷的', level: 'A1' },
  { cat: '形容词', ru: 'warm', zh: '温暖的', level: 'A1' },
  { cat: '形容词', ru: 'clean', zh: '干净的', level: 'A1' },
  { cat: '形容词', ru: 'dirty', zh: '脏的', level: 'A1' },
  { cat: '形容词', ru: 'easy', zh: '容易的', level: 'A1' },
  { cat: '形容词', ru: 'difficult', zh: '困难的', level: 'A2' },
  { cat: '形容词', ru: 'important', zh: '重要的', level: 'A2' },
  { cat: '形容词', ru: 'different', zh: '不同的', level: 'A1' },
  // 颜色
  { cat: '颜色', ru: 'red', zh: '红色', level: 'A1' },
  { cat: '颜色', ru: 'blue', zh: '蓝色', level: 'A1' },
  { cat: '颜色', ru: 'green', zh: '绿色', level: 'A1' },
  { cat: '颜色', ru: 'yellow', zh: '黄色', level: 'A1' },
  { cat: '颜色', ru: 'black', zh: '黑色', level: 'A1' },
  { cat: '颜色', ru: 'white', zh: '白色', level: 'A1' },
  { cat: '颜色', ru: 'orange', zh: '橙色', level: 'A1' },
  { cat: '颜色', ru: 'pink', zh: '粉色', level: 'A1' },
  // 食物饮料
  { cat: '食物饮料', ru: 'rice', zh: '米饭', level: 'A1' },
  { cat: '食物饮料', ru: 'noodles', zh: '面条', level: 'A2' },
  { cat: '食物饮料', ru: 'soup', zh: '汤', level: 'A1' },
  { cat: '食物饮料', ru: 'meat', zh: '肉', level: 'A1' },
  { cat: '食物饮料', ru: 'fish', zh: '鱼', level: 'A1' },
  { cat: '食物饮料', ru: 'egg', zh: '鸡蛋', level: 'A1' },
  { cat: '食物饮料', ru: 'cake', zh: '蛋糕', level: 'A1' },
  { cat: '食物饮料', ru: 'juice', zh: '果汁', level: 'A1' },
  { cat: '食物饮料', ru: 'beer', zh: '啤酒', level: 'A1' },
  { cat: '食物饮料', ru: 'wine', zh: '葡萄酒', level: 'A2' },
  { cat: '食物饮料', ru: 'breakfast', zh: '早餐', level: 'A1' },
  { cat: '食物饮料', ru: 'lunch', zh: '午餐', level: 'A1' },
  { cat: '食物饮料', ru: 'dinner', zh: '晚餐', level: 'A1' },
  { cat: '食物饮料', ru: 'dessert', zh: '甜点', level: 'B1' },
  // 星期月份
  { cat: '星期月份', ru: 'Monday', zh: '星期一', level: 'A1' },
  { cat: '星期月份', ru: 'Tuesday', zh: '星期二', level: 'A1' },
  { cat: '星期月份', ru: 'Wednesday', zh: '星期三', level: 'A1' },
  { cat: '星期月份', ru: 'Thursday', zh: '星期四', level: 'A1' },
  { cat: '星期月份', ru: 'Friday', zh: '星期五', level: 'A1' },
  { cat: '星期月份', ru: 'Saturday', zh: '星期六', level: 'A1' },
  { cat: '星期月份', ru: 'Sunday', zh: '星期日', level: 'A1' },
  { cat: '星期月份', ru: 'January', zh: '一月', level: 'A1' },
  { cat: '星期月份', ru: 'February', zh: '二月', level: 'A1' },
  { cat: '星期月份', ru: 'March', zh: '三月', level: 'A1' },
  { cat: '星期月份', ru: 'April', zh: '四月', level: 'A1' },
  { cat: '星期月份', ru: 'May', zh: '五月', level: 'A1' },
  { cat: '星期月份', ru: 'June', zh: '六月', level: 'A1' },
  { cat: '星期月份', ru: 'July', zh: '七月', level: 'A1' },
  { cat: '星期月份', ru: 'August', zh: '八月', level: 'A1' },
  { cat: '星期月份', ru: 'September', zh: '九月', level: 'A1' },
  { cat: '星期月份', ru: 'October', zh: '十月', level: 'A1' },
  { cat: '星期月份', ru: 'November', zh: '十一月', level: 'A1' },
  { cat: '星期月份', ru: 'December', zh: '十二月', level: 'A1' },
  // 家庭人物
  { cat: '家庭人物', ru: 'son', zh: '儿子', level: 'A1' },
  { cat: '家庭人物', ru: 'daughter', zh: '女儿', level: 'A1' },
  { cat: '家庭人物', ru: 'husband', zh: '丈夫', level: 'A1' },
  { cat: '家庭人物', ru: 'wife', zh: '妻子', level: 'A1' },
  { cat: '家庭人物', ru: 'grandfather', zh: '祖父', level: 'A1' },
  { cat: '家庭人物', ru: 'grandmother', zh: '祖母', level: 'A1' },
  { cat: '家庭人物', ru: 'uncle', zh: '叔叔 / 舅舅', level: 'A1' },
  { cat: '家庭人物', ru: 'aunt', zh: '阿姨 / 姑姑', level: 'A1' },
  // 身体
  { cat: '身体', ru: 'head', zh: '头', level: 'A1' },
  { cat: '身体', ru: 'eye', zh: '眼睛', level: 'A1' },
  { cat: '身体', ru: 'nose', zh: '鼻子', level: 'A1' },
  { cat: '身体', ru: 'mouth', zh: '嘴', level: 'A1' },
  { cat: '身体', ru: 'ear', zh: '耳朵', level: 'A1' },
  { cat: '身体', ru: 'hand', zh: '手', level: 'A1' },
  { cat: '身体', ru: 'foot', zh: '脚', level: 'A1' },
  { cat: '身体', ru: 'arm', zh: '手臂', level: 'A1' },
  { cat: '身体', ru: 'leg', zh: '腿', level: 'A1' },
  { cat: '身体', ru: 'heart', zh: '心', level: 'A1' },
  { cat: '身体', ru: 'hair', zh: '头发', level: 'A1' },
  { cat: '身体', ru: 'tooth', zh: '牙齿', level: 'A1' },
  // 地点场所
  { cat: '地点场所', ru: 'hospital', zh: '医院', level: 'A1' },
  { cat: '地点场所', ru: 'bank', zh: '银行', level: 'A1' },
  { cat: '地点场所', ru: 'restaurant', zh: '餐厅', level: 'A1' },
  { cat: '地点场所', ru: 'park', zh: '公园', level: 'A1' },
  { cat: '地点场所', ru: 'museum', zh: '博物馆', level: 'A2' },
  { cat: '地点场所', ru: 'station', zh: '车站', level: 'A1' },
  { cat: '地点场所', ru: 'airport', zh: '机场', level: 'A2' },
  { cat: '地点场所', ru: 'supermarket', zh: '超市', level: 'A1' },
  { cat: '地点场所', ru: 'hotel', zh: '旅馆', level: 'A1' },
  { cat: '地点场所', ru: 'library', zh: '图书馆', level: 'A1' },
  // 天气季节
  { cat: '天气季节', ru: 'weather', zh: '天气', level: 'A1' },
  { cat: '天气季节', ru: 'sun', zh: '太阳', level: 'A1' },
  { cat: '天气季节', ru: 'rain', zh: '雨', level: 'A1' },
  { cat: '天气季节', ru: 'snow', zh: '雪', level: 'A1' },
  { cat: '天气季节', ru: 'wind', zh: '风', level: 'A1' },
  { cat: '天气季节', ru: 'spring', zh: '春天', level: 'A1' },
  { cat: '天气季节', ru: 'summer', zh: '夏天', level: 'A1' },
  { cat: '天气季节', ru: 'autumn', zh: '秋天', level: 'A1' },
  { cat: '天气季节', ru: 'winter', zh: '冬天', level: 'A1' },
  // 时间
  { cat: '时间', ru: 'week', zh: '星期', level: 'A1' },
  { cat: '时间', ru: 'month', zh: '月', level: 'A1' },
  { cat: '时间', ru: 'year', zh: '年', level: 'A1' },
  { cat: '时间', ru: 'minute', zh: '分钟', level: 'A1' },
  { cat: '时间', ru: 'hour', zh: '小时', level: 'A1' },
  { cat: '时间', ru: 'season', zh: '季节', level: 'A2' },
  // 副词
  { cat: '副词', ru: 'always', zh: '总是', level: 'A1' },
  { cat: '副词', ru: 'never', zh: '从不', level: 'A1' },
  { cat: '副词', ru: 'often', zh: '经常', level: 'A1' },
  { cat: '副词', ru: 'sometimes', zh: '有时', level: 'A1' },
  { cat: '副词', ru: 'here', zh: '这里', level: 'A1' },
  { cat: '副词', ru: 'there', zh: '那里', level: 'A1' },
  { cat: '副词', ru: 'now', zh: '现在', level: 'A1' },
  { cat: '副词', ru: 'today', zh: '今天', level: 'A1' },
  { cat: '副词', ru: 'tomorrow', zh: '明天', level: 'A1' },
  { cat: '副词', ru: 'yesterday', zh: '昨天', level: 'A1' },
  // 职业
  { cat: '职业', ru: 'doctor', zh: '医生', level: 'A1' },
  { cat: '职业', ru: 'teacher', zh: '老师', level: 'A1' },
  { cat: '职业', ru: 'student', zh: '学生', level: 'A1' },
  { cat: '职业', ru: 'worker', zh: '工人', level: 'A1' },
  { cat: '职业', ru: 'farmer', zh: '农民', level: 'A1' },
  { cat: '职业', ru: 'driver', zh: '司机', level: 'A1' },
  { cat: '职业', ru: 'cook', zh: '厨师', level: 'A1' },
  { cat: '职业', ru: 'engineer', zh: '工程师', level: 'A2' },
  // 衣物
  { cat: '衣物', ru: 'shirt', zh: '衬衫', level: 'A1' },
  { cat: '衣物', ru: 'pants', zh: '裤子', level: 'A1' },
  { cat: '衣物', ru: 'dress', zh: '连衣裙', level: 'A1' },
  { cat: '衣物', ru: 'coat', zh: '外套', level: 'A1' },
  { cat: '衣物', ru: 'hat', zh: '帽子', level: 'A1' },
  { cat: '衣物', ru: 'shoes', zh: '鞋', level: 'A1' },
  { cat: '衣物', ru: 'socks', zh: '袜子', level: 'A1' },
  { cat: '衣物', ru: 'skirt', zh: '裙子', level: 'A1' },
  // 动物
  { cat: '动物', ru: 'horse', zh: '马', level: 'A1' },
  { cat: '动物', ru: 'cow', zh: '牛', level: 'A1' },
  { cat: '动物', ru: 'pig', zh: '猪', level: 'A1' },
  { cat: '动物', ru: 'bird', zh: '鸟', level: 'A1' },
  { cat: '动物', ru: 'duck', zh: '鸭子', level: 'A1' },
  { cat: '动物', ru: 'chicken', zh: '鸡', level: 'A1' },
  { cat: '动物', ru: 'sheep', zh: '绵羊', level: 'A1' },
  { cat: '动物', ru: 'bear', zh: '熊', level: 'A1' },
  // A2 词汇
  { cat: 'A2 词汇', ru: 'travel', zh: '旅行', level: 'A2' },
  { cat: 'A2 词汇', ru: 'hobby', zh: '爱好', level: 'A2' },
  { cat: 'A2 词汇', ru: 'future', zh: '未来', level: 'A2' },
  { cat: 'A2 词汇', ru: 'past', zh: '过去', level: 'A2' },
  { cat: 'A2 词汇', ru: 'price', zh: '价格', level: 'A2' },
  { cat: 'A2 词汇', ru: 'ticket', zh: '票', level: 'A2' },
  { cat: 'A2 词汇', ru: 'gift', zh: '礼物', level: 'A2' },
  { cat: 'A2 词汇', ru: 'mistake', zh: '错误', level: 'A2' },
  { cat: 'A2 词汇', ru: 'wedding', zh: '婚礼', level: 'A2' },
  { cat: 'A2 词汇', ru: 'holiday', zh: '假日', level: 'A2' },

  // ========== B1 词汇 ==========
  { cat: 'B1 词汇', ru: 'experience', zh: '经验 / 经历', level: 'B1' },
  { cat: 'B1 词汇', ru: 'environment', zh: '环境', level: 'B1' },
  { cat: 'B1 词汇', ru: 'opportunity', zh: '机会', level: 'B1' },
  { cat: 'B1 词汇', ru: 'decision', zh: '决定', level: 'B1' },
  { cat: 'B1 词汇', ru: 'relationship', zh: '关系', level: 'B1' },
  { cat: 'B1 词汇', ru: 'achieve', zh: '实现 / 达到', level: 'B1' },
  { cat: 'B1 词汇', ru: 'improve', zh: '改进 / 提高', level: 'B1' },
  { cat: 'B1 词汇', ru: 'describe', zh: '描述', level: 'B1' },
  { cat: 'B1 词汇', ru: 'accept', zh: '接受', level: 'B1' },
  { cat: 'B1 词汇', ru: 'avoid', zh: '避免', level: 'B1' },
  { cat: 'B1 词汇', ru: 'purpose', zh: '目的', level: 'B1' },
  { cat: 'B1 词汇', ru: 'habit', zh: '习惯', level: 'B1' },
  { cat: 'B1 词汇', ru: 'society', zh: '社会', level: 'B1' },
  { cat: 'B1 词汇', ru: 'culture', zh: '文化', level: 'B1' },
  { cat: 'B1 词汇', ru: 'education', zh: '教育', level: 'B1' },
  { cat: 'B1 词汇', ru: 'technology', zh: '技术', level: 'B1' },
  { cat: 'B1 词汇', ru: 'government', zh: '政府', level: 'B1' },
  { cat: 'B1 词汇', ru: 'community', zh: '社区', level: 'B1' },
  { cat: 'B1 词汇', ru: 'solution', zh: '解决方案', level: 'B1' },
  { cat: 'B1 词汇', ru: 'global', zh: '全球的', level: 'B1' },

  // ========== B2 词汇 ==========
  { cat: 'B2 词汇', ru: 'research', zh: '研究', level: 'B2' },
  { cat: 'B2 词汇', ru: 'development', zh: '发展 / 开发', level: 'B2' },
  { cat: 'B2 词汇', ru: 'influence', zh: '影响', level: 'B2' },
  { cat: 'B2 词汇', ru: 'argument', zh: '争论 / 论据', level: 'B2' },
  { cat: 'B2 词汇', ru: 'conclusion', zh: '结论', level: 'B2' },
  { cat: 'B2 词汇', ru: 'significant', zh: '显著的 / 重要的', level: 'B2' },
  { cat: 'B2 词汇', ru: 'efficient', zh: '高效的', level: 'B2' },
  { cat: 'B2 词汇', ru: 'determine', zh: '决定 / 确定', level: 'B2' },
  { cat: 'B2 词汇', ru: 'maintain', zh: '维持 / 保持', level: 'B2' },
  { cat: 'B2 词汇', ru: 'assume', zh: '假设 / 认为', level: 'B2' },
  { cat: 'B2 词汇', ru: 'expand', zh: '扩展 / 扩大', level: 'B2' },
  { cat: 'B2 词汇', ru: 'generate', zh: '产生 / 生成', level: 'B2' },
  { cat: 'B2 词汇', ru: 'perspective', zh: '视角 / 观点', level: 'B2' },
  { cat: 'B2 词汇', ru: 'phenomenon', zh: '现象', level: 'B2' },
  { cat: 'B2 词汇', ru: 'sustainable', zh: '可持续的', level: 'B2' },
  { cat: 'B2 词汇', ru: 'imply', zh: '暗示', level: 'B2' },
  { cat: 'B2 词汇', ru: 'assess', zh: '评估', level: 'B2' },
  { cat: 'B2 词汇', ru: 'enhance', zh: '增强', level: 'B2' },

  // ========== C1 词汇 ==========
  { cat: 'C1 词汇', ru: 'comprehensive', zh: '全面的 / 综合的', level: 'C1' },
  { cat: 'C1 词汇', ru: 'inevitable', zh: '不可避免的', level: 'C1' },
  { cat: 'C1 词汇', ru: 'implement', zh: '实施 / 执行', level: 'C1' },
  { cat: 'C1 词汇', ru: 'controversial', zh: '有争议的', level: 'C1' },
  { cat: 'C1 词汇', ru: 'considerable', zh: '相当大的', level: 'C1' },
  { cat: 'C1 词汇', ru: 'advocate', zh: '提倡 / 拥护', level: 'C1' },
  { cat: 'C1 词汇', ru: 'undermine', zh: '削弱 / 损害', level: 'C1' },
  { cat: 'C1 词汇', ru: 'sophisticated', zh: '精密的 / 复杂的', level: 'C1' },
  { cat: 'C1 词汇', ru: 'resilience', zh: '韧性 / 恢复力', level: 'C1' },
  { cat: 'C1 词汇', ru: 'paradigm', zh: '范式', level: 'C1' },
  { cat: 'C1 词汇', ru: 'inherent', zh: '固有的', level: 'C1' },
  { cat: 'C1 词汇', ru: 'mitigate', zh: '缓解 / 减轻', level: 'C1' },

  // ========== C2 词汇 ==========
  { cat: 'C2 词汇', ru: 'meticulous', zh: '一丝不苟的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'ambiguous', zh: '模棱两可的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'eloquent', zh: '雄辩的 / 有口才的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'contemplate', zh: '沉思 / 深思', level: 'C2' },
  { cat: 'C2 词汇', ru: 'scrutinize', zh: '仔细审视', level: 'C2' },
  { cat: 'C2 词汇', ru: 'obsolete', zh: '过时的 / 废弃的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'pragmatic', zh: '务实的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'profound', zh: '深刻的 / 深远的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'ephemeral', zh: '短暂的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'quintessential', zh: '典型的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'ubiquitous', zh: '无处不在的', level: 'C2' },
  { cat: 'C2 词汇', ru: 'pernicious', zh: '有害的 / 恶性的', level: 'C2' },
];

// ========== 词库包 2:主题场景(30 个生活场景) ==========
window.VOCAB_SCENES = [
  { cat: '场景·就医看病', ru: 'patient', zh: '病人' },
  { cat: '场景·就医看病', ru: 'medicine', zh: '药' },
  { cat: '场景·就医看病', ru: 'fever', zh: '发烧' },
  { cat: '场景·就医看病', ru: 'clinic', zh: '诊所' },
  { cat: '场景·银行金融', ru: 'deposit', zh: '存款' },
  { cat: '场景·银行金融', ru: 'withdraw', zh: '取款' },
  { cat: '场景·银行金融', ru: 'transfer', zh: '转账' },
  { cat: '场景·银行金融', ru: 'interest', zh: '利息' },
  { cat: '场景·交通出行', ru: 'traffic', zh: '交通' },
  { cat: '场景·交通出行', ru: 'traffic jam', zh: '堵车' },
  { cat: '场景·交通出行', ru: 'fare', zh: '车费' },
  { cat: '场景·交通出行', ru: 'platform', zh: '站台' },
  { cat: '场景·购物', ru: 'discount', zh: '折扣' },
  { cat: '场景·购物', ru: 'refund', zh: '退款' },
  { cat: '场景·购物', ru: 'receipt', zh: '收据' },
  { cat: '场景·购物', ru: 'try on', zh: '试穿' },
  { cat: '场景·餐厅', ru: 'order', zh: '点单' },
  { cat: '场景·餐厅', ru: 'waiter', zh: '服务员' },
  { cat: '场景·餐厅', ru: 'menu', zh: '菜单' },
  { cat: '场景·餐厅', ru: 'tip', zh: '小费' },
  { cat: '场景·酒店住宿', ru: 'check-in', zh: '入住' },
  { cat: '场景·酒店住宿', ru: 'check-out', zh: '退房' },
  { cat: '场景·酒店住宿', ru: 'reservation', zh: '预订' },
  { cat: '场景·酒店住宿', ru: 'luggage', zh: '行李' },
  { cat: '场景·机场', ru: 'flight', zh: '航班' },
  { cat: '场景·机场', ru: 'departure', zh: '出发' },
  { cat: '场景·机场', ru: 'arrival', zh: '到达' },
  { cat: '场景·机场', ru: 'passport', zh: '护照' },
  { cat: '场景·问路', ru: 'straight', zh: '直走' },
  { cat: '场景·问路', ru: 'left', zh: '左' },
  { cat: '场景·问路', ru: 'right', zh: '右' },
  { cat: '场景·问路', ru: 'corner', zh: '拐角' },
  { cat: '场景·工作职场', ru: 'meeting', zh: '会议' },
  { cat: '场景·工作职场', ru: 'salary', zh: '工资' },
  { cat: '场景·工作职场', ru: 'colleague', zh: '同事' },
  { cat: '场景·工作职场', ru: 'boss', zh: '老板' },
  { cat: '场景·学习考试', ru: 'exam', zh: '考试' },
  { cat: '场景·学习考试', ru: 'homework', zh: '作业' },
  { cat: '场景·学习考试', ru: 'lecture', zh: '讲座 / 课' },
  { cat: '场景·学习考试', ru: 'grade', zh: '成绩' },
  { cat: '场景·租房住房', ru: 'rent', zh: '租金' },
  { cat: '场景·租房住房', ru: 'landlord', zh: '房东' },
  { cat: '场景·租房住房', ru: 'contract', zh: '合同' },
  { cat: '场景·租房住房', ru: 'move', zh: '搬家' },
  { cat: '场景·运动健身', ru: 'gym', zh: '健身房' },
  { cat: '场景·运动健身', ru: 'exercise', zh: '锻炼' },
  { cat: '场景·运动健身', ru: 'swimming', zh: '游泳' },
  { cat: '场景·运动健身', ru: 'match', zh: '比赛' },
  { cat: '场景·网络手机', ru: 'password', zh: '密码' },
  { cat: '场景·网络手机', ru: 'account', zh: '账户' },
  { cat: '场景·网络手机', ru: 'notification', zh: '通知' },
  { cat: '场景·网络手机', ru: 'app', zh: '应用程序' },
  { cat: '场景·情绪心情', ru: 'joy', zh: '喜悦' },
  { cat: '场景·情绪心情', ru: 'sadness', zh: '悲伤' },
  { cat: '场景·情绪心情', ru: 'fear', zh: '恐惧' },
  { cat: '场景·情绪心情', ru: 'surprise', zh: '惊讶' },
  { cat: '场景·时间日期', ru: 'date', zh: '日期' },
  { cat: '场景·时间日期', ru: 'weekend', zh: '周末' },
  { cat: '场景·时间日期', ru: 'midnight', zh: '午夜' },
  { cat: '场景·时间日期', ru: 'deadline', zh: '截止日期' },
  { cat: '场景·家庭生活', ru: 'baby', zh: '婴儿' },
  { cat: '场景·家庭生活', ru: 'wedding', zh: '婚礼' },
  { cat: '场景·家庭生活', ru: 'birthday', zh: '生日' },
  { cat: '场景·家庭生活', ru: 'relative', zh: '亲戚' },
  { cat: '场景·美容理发', ru: 'haircut', zh: '理发' },
  { cat: '场景·美容理发', ru: 'shampoo', zh: '洗发水' },
  { cat: '场景·美容理发', ru: 'towel', zh: '毛巾' },
  { cat: '场景·美容理发', ru: 'mirror', zh: '镜子' },
  { cat: '场景·修理服务', ru: 'repair', zh: '修理' },
  { cat: '场景·修理服务', ru: 'tool', zh: '工具' },
  { cat: '场景·修理服务', ru: 'electricity', zh: '电' },
  { cat: '场景·修理服务', ru: 'guarantee', zh: '保修' },
  { cat: '场景·警察求助', ru: 'police', zh: '警察' },
  { cat: '场景·警察求助', ru: 'thief', zh: '小偷' },
  { cat: '场景·警察求助', ru: 'report', zh: '报案' },
  { cat: '场景·警察求助', ru: 'fine', zh: '罚款' },
  { cat: '场景·天气气候', ru: 'forecast', zh: '预报' },
  { cat: '场景·天气气候', ru: 'fog', zh: '雾' },
  { cat: '场景·天气气候', ru: 'storm', zh: '暴风雨' },
  { cat: '场景·天气气候', ru: 'degree', zh: '温度 / 度数' },
  { cat: '场景·衣物鞋帽', ru: 'fashion', zh: '时尚' },
  { cat: '场景·衣物鞋帽', ru: 'style', zh: '风格' },
  { cat: '场景·衣物鞋帽', ru: 'button', zh: '纽扣' },
  { cat: '场景·衣物鞋帽', ru: 'pocket', zh: '口袋' },
  { cat: '场景·节日庆典', ru: 'festival', zh: '节日' },
  { cat: '场景·节日庆典', ru: 'gift', zh: '礼物' },
  { cat: '场景·节日庆典', ru: 'fireworks', zh: '烟花' },
  { cat: '场景·节日庆典', ru: 'celebrate', zh: '庆祝' },
  { cat: '场景·自然环境', ru: 'nature', zh: '自然' },
  { cat: '场景·自然环境', ru: 'forest', zh: '森林' },
  { cat: '场景·自然环境', ru: 'river', zh: '河流' },
  { cat: '场景·自然环境', ru: 'pollution', zh: '污染' },
  { cat: '场景·动物宠物', ru: 'pet', zh: '宠物' },
  { cat: '场景·动物宠物', ru: 'parrot', zh: '鹦鹉' },
  { cat: '场景·动物宠物', ru: 'cage', zh: '笼子' },
  { cat: '场景·动物宠物', ru: 'vet', zh: '兽医' },
  { cat: '场景·学校课堂', ru: 'classroom', zh: '教室' },
  { cat: '场景·学校课堂', ru: 'bell', zh: '铃声' },
  { cat: '场景·学校课堂', ru: 'chalk', zh: '粉笔' },
  { cat: '场景·学校课堂', ru: 'classmate', zh: '同学' },
  { cat: '场景·厨房做饭', ru: 'cooking', zh: '烹饪' },
  { cat: '场景·厨房做饭', ru: 'fry', zh: '煎炸' },
  { cat: '场景·厨房做饭', ru: 'knife', zh: '刀' },
  { cat: '场景·厨房做饭', ru: 'pot', zh: '锅' },
  { cat: '场景·打扫家务', ru: 'sweep', zh: '扫地' },
  { cat: '场景·打扫家务', ru: 'mop', zh: '拖地' },
  { cat: '场景·打扫家务', ru: 'dust', zh: '灰尘' },
  { cat: '场景·打扫家务', ru: 'tidy', zh: '整洁的' },
  { cat: '场景·约会交友', ru: 'romance', zh: '恋爱 / 恋情' },
  { cat: '场景·约会交友', ru: 'kiss', zh: '吻' },
  { cat: '场景·约会交友', ru: 'hug', zh: '拥抱' },
  { cat: '场景·约会交友', ru: 'love', zh: '爱' },
  { cat: '场景·邮局快递', ru: 'post office', zh: '邮局' },
  { cat: '场景·邮局快递', ru: 'parcel', zh: '包裹' },
  { cat: '场景·邮局快递', ru: 'envelope', zh: '信封' },
  { cat: '场景·邮局快递', ru: 'delivery', zh: '配送' },
  { cat: '场景·旅游观光', ru: 'sightseeing', zh: '观光' },
  { cat: '场景·旅游观光', ru: 'guide', zh: '导游' },
  { cat: '场景·旅游观光', ru: 'souvenir', zh: '纪念品' },
  { cat: '场景·旅游观光', ru: 'map', zh: '地图' },
];

// ========== 词库包 3:高频词汇(按频率精选) ==========
window.VOCAB_FREQ = [
  { cat: '高频·虚词', ru: 'the', zh: '定冠词(这/那)' },
  { cat: '高频·虚词', ru: 'a', zh: '一个' },
  { cat: '高频·虚词', ru: 'and', zh: '和' },
  { cat: '高频·虚词', ru: 'or', zh: '或者' },
  { cat: '高频·虚词', ru: 'but', zh: '但是' },
  { cat: '高频·虚词', ru: 'because', zh: '因为' },
  { cat: '高频·虚词', ru: 'so', zh: '所以' },
  { cat: '高频·虚词', ru: 'if', zh: '如果' },
  { cat: '高频·虚词', ru: 'when', zh: '当…时' },
  { cat: '高频·虚词', ru: 'while', zh: '当… / 而' },
  { cat: '高频·虚词', ru: 'after', zh: '在…之后' },
  { cat: '高频·虚词', ru: 'before', zh: '在…之前' },
  { cat: '高频·虚词', ru: 'with', zh: '和…一起' },
  { cat: '高频·虚词', ru: 'without', zh: '没有' },
  { cat: '高频·虚词', ru: 'about', zh: '关于' },
  { cat: '高频·代词', ru: 'my', zh: '我的' },
  { cat: '高频·代词', ru: 'your', zh: '你的' },
  { cat: '高频·代词', ru: 'his', zh: '他的' },
  { cat: '高频·代词', ru: 'her', zh: '她的' },
  { cat: '高频·代词', ru: 'its', zh: '它的' },
  { cat: '高频·代词', ru: 'our', zh: '我们的' },
  { cat: '高频·代词', ru: 'their', zh: '他们的' },
  { cat: '高频·代词', ru: 'which', zh: '哪个' },
  { cat: '高频·代词', ru: 'whose', zh: '谁的' },
  { cat: '高频·代词', ru: 'myself', zh: '我自己' },
  { cat: '高频·动词', ru: 'get', zh: '得到' },
  { cat: '高频·动词', ru: 'make', zh: '制作' },
  { cat: '高频·动词', ru: 'take', zh: '拿' },
  { cat: '高频·动词', ru: 'give', zh: '给' },
  { cat: '高频·动词', ru: 'find', zh: '找到' },
  { cat: '高频·动词', ru: 'tell', zh: '告诉' },
  { cat: '高频·动词', ru: 'ask', zh: '问' },
  { cat: '高频·动词', ru: 'say', zh: '说' },
  { cat: '高频·动词', ru: 'mean', zh: '意思是' },
  { cat: '高频·动词', ru: 'need', zh: '需要' },
  { cat: '高频·动词', ru: 'use', zh: '使用' },
  { cat: '高频·动词', ru: 'try', zh: '尝试' },
  { cat: '高频·动词', ru: 'leave', zh: '离开' },
  { cat: '高频·动词', ru: 'keep', zh: '保持' },
  { cat: '高频·动词', ru: 'put', zh: '放' },
  { cat: '高频·名词', ru: 'thing', zh: '事情 / 东西' },
  { cat: '高频·名词', ru: 'way', zh: '方式 / 道路' },
  { cat: '高频·名词', ru: 'people', zh: '人们' },
  { cat: '高频·名词', ru: 'world', zh: '世界' },
  { cat: '高频·名词', ru: 'life', zh: '生活' },
  { cat: '高频·名词', ru: 'part', zh: '部分' },
  { cat: '高频·名词', ru: 'problem', zh: '问题(麻烦)' },
  { cat: '高频·名词', ru: 'question', zh: '问题(提问)' },
  { cat: '高频·名词', ru: 'answer', zh: '回答' },
  { cat: '高频·名词', ru: 'place', zh: '地方' },
  { cat: '高频·名词', ru: 'home', zh: '家' },
  { cat: '高频·名词', ru: 'room', zh: '房间' },
  { cat: '高频·名词', ru: 'food', zh: '食物' },
  { cat: '高频·名词', ru: 'job', zh: '工作' },
  { cat: '高频·名词', ru: 'news', zh: '新闻' },
  { cat: '高频·形容词', ru: 'other', zh: '其他的' },
  { cat: '高频·形容词', ru: 'same', zh: '相同的' },
  { cat: '高频·形容词', ru: 'special', zh: '特别的' },
  { cat: '高频·形容词', ru: 'free', zh: '自由的 / 免费的' },
  { cat: '高频·形容词', ru: 'full', zh: '满的' },
  { cat: '高频·形容词', ru: 'sure', zh: '确定的' },
  { cat: '高频·形容词', ru: 'real', zh: '真实的' },
  { cat: '高频·形容词', ru: 'true', zh: '真实的' },
  { cat: '高频·形容词', ru: 'right', zh: '正确的' },
  { cat: '高频·形容词', ru: 'wrong', zh: '错误的' },
  { cat: '高频·形容词', ru: 'great', zh: '很棒的' },
  { cat: '高频·形容词', ru: 'high', zh: '高的' },
  { cat: '高频·形容词', ru: 'low', zh: '低的' },
  { cat: '高频·形容词', ru: 'late', zh: '迟的' },
  { cat: '高频·形容词', ru: 'early', zh: '早的' },
  { cat: '高频·副词', ru: 'also', zh: '也' },
  { cat: '高频·副词', ru: 'just', zh: '刚刚 / 只' },
  { cat: '高频·副词', ru: 'only', zh: '只' },
  { cat: '高频·副词', ru: 'very', zh: '非常' },
  { cat: '高频·副词', ru: 'too', zh: '太 / 也' },
  { cat: '高频·副词', ru: 'again', zh: '再次' },
  { cat: '高频·副词', ru: 'soon', zh: '很快' },
  { cat: '高频·副词', ru: 'later', zh: '稍后' },
  { cat: '高频·副词', ru: 'together', zh: '一起' },
  { cat: '高频·副词', ru: 'really', zh: '真的' },
  { cat: '高频·副词', ru: 'quite', zh: '相当' },
  { cat: '高频·副词', ru: 'almost', zh: '几乎' },
  { cat: '高频·副词', ru: 'enough', zh: '足够' },
  { cat: '高频·副词', ru: 'maybe', zh: '也许' },
  { cat: '高频·副词', ru: 'already', zh: '已经' },
];

// ========== 词库包 4:易错口语(带 note 辨析) ==========
window.VOCAB_MISTAKES = [
  // 易混词
  { cat: '易错·形近词', ru: 'its', zh: '它的', note: "its(它的)无撇号;it's = it is(它是)。✗ The dog wagged it's tail." },
  { cat: '易错·形近词', ru: 'there', zh: '那里', note: 'there(那里)/their(他们的)/they\'re(他们是)同音。✗ There books are here. → Their' },
  { cat: '易错·形近词', ru: 'affect', zh: '影响(动词)', note: 'affect(动词,影响)/effect(名词,效果)。✗ The medicine effected me. → affected' },
  { cat: '易错·形近词', ru: 'raise', zh: '抬起 / 筹集', note: 'raise(及物:raise your hand)/rise(不及物:the sun rises)。✗ The sun raises.' },
  { cat: '易错·形近词', ru: 'hear', zh: '听见', note: 'hear(无意听见)/listen(有意听,listen to)。✗ I heard to music. → listened to' },
  { cat: '易错·形近词', ru: 'look', zh: '看(看的过程)', note: 'look(看,look at)/watch(观看)/see(看见)。✗ I look TV. → watch' },
  { cat: '易错·形近词', ru: 'say', zh: '说(内容)', note: 'say sth(说内容)/tell sb(告诉某人)/speak a language(说语言)。✗ He said me. → told' },
  { cat: '易错·形近词', ru: 'quiet', zh: '安静的', note: 'quiet(安静)/quite(相当)。✗ The room is quite. → quiet' },
  { cat: '易错·形近词', ru: 'lose', zh: '丢失', note: 'lose(丢失)/loose(松的)。✗ I loose my key. → lose' },
  { cat: '易错·形近词', ru: 'beside', zh: '在…旁边', note: 'beside(在…旁边)/besides(此外)。✗ Beside English, I learn Russian. → Besides' },
  // 搭配
  { cat: '易错·搭配', ru: 'depend', zh: '依赖', note: 'depend on。✗ depend of。It depends on you.' },
  { cat: '易错·搭配', ru: 'married', zh: '已婚的', note: 'married to sb。✗ married with。She is married to Tom.' },
  { cat: '易错·搭配', ru: 'insist', zh: '坚持', note: 'insist on。✗ insist of。He insisted on paying.' },
  { cat: '易错·搭配', ru: 'arrive', zh: '到达', note: 'arrive in(大地方)/arrive at(小地方)。✗ arrive to。They arrived at the station.' },
  // 语法易错
  { cat: '易错·用法', ru: 'much', zh: '许多', note: 'much + 不可数,many + 可数。✗ much books → many books' },
  { cat: '易错·用法', ru: 'fewer', zh: '更少', note: 'fewer + 可数,less + 不可数。✗ less people → fewer people' },
  { cat: '易错·用法', ru: 'borrow', zh: '借入', note: 'borrow from(借入)/lend to(借出)。✗ Can you borrow me a pen? → lend' },
  { cat: '易错·用法', ru: 'lie', zh: '躺', note: 'lie(躺,过去式 lay)/lay(放,过去式 laid)。✗ I laid on the bed? → lay(lie 的过去式)' },
  { cat: '易错·用法', ru: 'fun', zh: '乐趣', note: 'fun 是名词,✗ very fun 不严谨;建议 great fun / enjoyable。It was great fun!' },
  { cat: '易错·用法', ru: 'advice', zh: '建议', note: 'advice 不可数,✗ advices;a piece of advice。advise 才是动词。' },
  // 重音
  { cat: '易错·重音', ru: 'record', zh: '唱片(名词)', note: "名词 'record(重音在前);动词 re'cord(重音在后,录制)。✗ 混淆重音。" },
  { cat: '易错·重音', ru: 'present', zh: '礼物(名词)', note: "名词/形容词 'present(重音在前);动词 pre'sent(重音在后,展示)。✗ 混淆。" },
  { cat: '易错·重音', ru: 'photograph', zh: '照片', note: "'photograph 重音在第 1 音节 PHO-to-graph;✗ pho-TO-graph。photography 重音在 -to-。" },
  { cat: '易错·重音', ru: 'comfortable', zh: '舒适的', note: "正确 'comfortable(3 音节 COM-for-ta-ble);✗ com-FORT-a-ble 四音节是常见错误。" },
];

window.PHRASES = [
  { name: '问候寒暄', items: [
    { ru: 'Hello!', zh: '你好!' },
    { ru: 'How are you?', zh: '你好吗?' },
    { ru: 'Nice to meet you!', zh: '很高兴认识你!' },
    { ru: 'See you!', zh: '再见!' },
    { ru: 'Good luck!', zh: '祝你好运!' },
  ]},
  { name: '礼貌用语', items: [
    { ru: 'Thank you very much!', zh: '非常感谢!' },
    { ru: "You're welcome.", zh: '不客气。' },
    { ru: 'Excuse me.', zh: '打扰一下。' },
    { ru: "It's OK.", zh: '没关系。' },
  ]},
  { name: '自我介绍', items: [
    { ru: 'My name is Anna.', zh: '我叫安娜。' },
    { ru: "What's your name?", zh: '你叫什么名字?' },
    { ru: "I'm from China.", zh: '我来自中国。' },
    { ru: 'I am a student.', zh: '我是学生。' },
  ]},
];

window.SENTENCES = [
  { ru: 'Hello! My name is Anna.', zh: '你好!我叫安娜。' },
  { ru: "What's your name?", zh: '你叫什么名字?' },
  { ru: "I'm from China.", zh: '我来自中国。' },
  { ru: "I'm learning English.", zh: '我在学英语。' },
  { ru: 'Where are you from?', zh: '你来自哪里?' },
  { ru: 'Nice to meet you!', zh: '很高兴认识你!' },
  { ru: 'How old are you?', zh: '你多大了?' },
  { ru: 'I like reading books.', zh: '我喜欢读书。' },
  { ru: 'See you tomorrow!', zh: '明天见!' },
];

window.TONGUE_TWISTERS = [
  { ru: 'She sells seashells by the seashore.', zh: '她在海边卖贝壳。', tip: '练 s 和 sh 的对比' },
  { ru: 'Peter Piper picked a peck of pickled peppers.', zh: '彼得·派珀摘了许多腌辣椒。', tip: '练 p 的连读' },
];

window.DIALOGUES = [
  {
    title: '见面问候',
    lines: [
      { who: 'Amy', ru: 'Hi! Nice to meet you!', zh: '嗨!很高兴认识你!' },
      { who: 'Ben', ru: 'Hi! How are you?', zh: '嗨!你好吗?' },
      { who: 'Amy', ru: "I'm fine, thank you. And you?", zh: '我很好,谢谢。你呢?' },
      { who: 'Ben', ru: 'Very well, thanks.', zh: '非常好,谢谢。' },
    ],
  },
  {
    title: '在商店',
    lines: [
      { who: 'Assistant', ru: 'Can I help you?', zh: '需要帮忙吗?' },
      { who: 'Customer', ru: 'How much is this book?', zh: '这本书多少钱?' },
      { who: 'Assistant', ru: "It's ten dollars.", zh: '十美元。' },
      { who: 'Customer', ru: "I'll take it.", zh: '我买了。' },
    ],
  },
  {
    title: '在餐厅',
    lines: [
      { who: 'Waiter', ru: 'What would you like to order?', zh: '您想点什么?' },
      { who: 'Guest', ru: "I'd like a coffee and a sandwich, please.", zh: '我想要一杯咖啡和一个三明治。' },
      { who: 'Waiter', ru: 'Anything else?', zh: '还需要别的吗?' },
      { who: 'Guest', ru: 'No, thanks.', zh: '不用了,谢谢。' },
    ],
  },
];
